language: node_js
sudo: required
dist: trusty
node_js:
  - "8.9.1"

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo dpkg -i google-chrome*.deb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
